name: Farm 1

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  farm1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: commit farm
        run: |
          echo $(date) >> farm.txt
          git config user.name "frhndevweb"
          git config user.email "frhndevweb@gmail.com"
          git add .
          git commit -m "farm $RANDOM"
          git push
