name: Graph Farm

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  farm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update log and README
        run: |
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          echo "[$DATE] farm commit executed" >> farm.log

          sed -i "/<!-- FARM_STATUS_START -->/,/<!-- FARM_STATUS_END -->/c\<!-- FARM_STATUS_START -->\nLast farm run: $DATE\n<!-- FARM_STATUS_END -->" README.md

      - name: Commit
        run: |
          git config user.name "frhndevweb"
          git config user.email "frhndevweb@gmail.com"

          git add README.md farm.log

          git commit -m "🌱 farm: $DATE" || echo "No changes"

          git push
